### PR TITLE
Development/hussein

### PR DESCRIPTION
**Pull request by HusseinAlsakkaf**
Thank you for contributing! To help the review process, please provide the following:

### Proposal
•	Completing Lessonpage and adding SigningUpTable component to it. 
•	Adding a fake Json file that provides signing up fake data to the Lessonpage which will be replaced by an API.
•	Deleting the old mechanism of navigation between pages from App component, now that it is replaced by the use of ( link to: )
•	Coding the mechanism in Main, LessonPage and UpcomingLessons components to pass the lesson id from the UpcomingLesson component  to the LessonPage component when the button is clicked. 
•	Adding mentors and team members as contributors in the package json file along with links to each member’s github. 

### Related
n/a

### Checklist

- [x] I have read the [code of conduct] and [contributing guide]
- [x] I have made this pull request to the `master` branch
- [x] I have run all of the automated validation using `npm run ship`
- [x] I have added myself to the `"contributors"` list in the `package.json` (or do not want to)

[code of conduct]: https://github.com/textbook/starter-kit/blob/master/.github/CODE_OF_CONDUCT.md
[contributing guide]: https://github.com/textbook/starter-kit/blob/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Review by pchan2 — APPROVED** [review]
Thanks.

**Review by nouri89 — APPROVED** [review]

**Review by AliHaider-1 — CHANGES_REQUESTED** [review]
Hi Hussein
There are some logs above which show you 
that your branch and changes have   some errors related to deployment. I am attaching the logs of errors here. so you can see and sort out those errors and then i will merge your branch to master.

Screenshot (470)

**Review by AliHaider-1 — COMMENTED** [review]
Hi Hussein,
There are some conflicts in your branch lesson table file. Can you resolve those conflicts.

**Comment by HusseinAlsakkaf** [comment]
@ Ali, Master branch is broken. It doesn't fetch data to the UpcomingLessons table check your latest pull request.

**Review by AliHaider-1 — APPROVED** [review]

**Comment by AliHaider-1** [comment]
Thanks Hussein. Well Done.

**Pull request merged**
