### PR TITLE
adding database files

### PR DESCRIPTION
**Pull request by nouri89**
Thank you for contributing! To help the review process, please provide the following:

### Proposal
pushing database file to the repo.

### Related
N/A
### Checklist

- [x] I have read the [code of conduct] and [contributing guide]
- [x] I have made this pull request to the `master` branch
- [x] I have run all of the automated validation using `npm run ship`
- [x] I have added myself to the `"contributors"` list in the `package.json` (or do not want to)

[code of conduct]: https://github.com/textbook/starter-kit/blob/master/.github/CODE_OF_CONDUCT.md
[contributing guide]: https://github.com/textbook/starter-kit/blob/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Review by AliHaider-1 — APPROVED** [review]
Well Done Nouri

**Review by HusseinAlsakkaf — APPROVED** [review]
Well done

**Comment by nouri89** [comment]
Thank you guys

**Comment by nouri89** [comment]
thanks

**Pull request merged**
